//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.04.12 at 03:57:27 PM CEST
//

package at.aau.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/** */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {"method", "counter"})
@XmlRootElement(name = "class")
public class Class {

  @XmlAttribute(name = "name", required = true)
  @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
  protected String name;

  @XmlAttribute(name = "sourcefilename")
  @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
  protected String sourcefilename;

  protected List<Method> method;
  protected List<Counter> counter;

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    name = value;
  }

  /**
   * Gets the value of the sourcefilename property.
   *
   * @return possible object is {@link String }
   */
  public String getSourcefilename() {
    return sourcefilename;
  }

  /**
   * Sets the value of the sourcefilename property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSourcefilename(String value) {
    sourcefilename = value;
  }

  /**
   * Gets the value of the method property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a {@code set} method for the method property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getMethod().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Method }
   */
  public List<Method> getMethod() {
    if (method == null) {
      method = new ArrayList<Method>();
    }
    return method;
  }

  /**
   * Gets the value of the counter property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a {@code set} method for the counter property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getCounter().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Counter }
   */
  public List<Counter> getCounter() {
    if (counter == null) {
      counter = new ArrayList<Counter>();
    }
    return counter;
  }
}
