//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.12 at 03:57:27 PM CEST 
//


package at.aau.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "line")
public class Line {

    @XmlAttribute(name = "nr", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nr;
    @XmlAttribute(name = "mi")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String mi;
    @XmlAttribute(name = "ci")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ci;
    @XmlAttribute(name = "mb")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String mb;
    @XmlAttribute(name = "cb")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cb;

    /**
     * Gets the value of the nr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNr() {
        return nr;
    }

    /**
     * Sets the value of the nr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNr(String value) {
        this.nr = value;
    }

    /**
     * Gets the value of the mi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMi() {
        return mi;
    }

    /**
     * Sets the value of the mi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMi(String value) {
        this.mi = value;
    }

    /**
     * Gets the value of the ci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCi() {
        return ci;
    }

    /**
     * Sets the value of the ci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCi(String value) {
        this.ci = value;
    }

    /**
     * Gets the value of the mb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMb() {
        return mb;
    }

    /**
     * Sets the value of the mb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMb(String value) {
        this.mb = value;
    }

    /**
     * Gets the value of the cb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCb() {
        return cb;
    }

    /**
     * Sets the value of the cb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCb(String value) {
        this.cb = value;
    }

}
